# Generated by Django 2.1.7 on 2019-03-25 10:13

import django.db.models.manager
from django.db import migrations, models

import colorful.fields


class Migration(migrations.Migration):

    dependencies = [("puput", "0002_auto_20150919_0925")]

    operations = [
        migrations.AlterModelManagers(name="blogpage", managers=[("extra", django.db.models.manager.Manager())]),
        migrations.AddField(
            model_name="blogpage",
            name="main_color",
            field=colorful.fields.RGBColorField(default="#4D6AE0", verbose_name="Blog Main Color"),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="short_feed_description",
            field=models.BooleanField(default=True, verbose_name="Use short description in feeds"),
        ),
    ]
