# Generated by Django 1.10.5 on 2017-09-12 09:28

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puput", "0003_add_short_feed_description_to_blog_page"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="blogpage",
            managers=[
                ("extra", django.db.models.manager.Manager()),
            ],
        ),
    ]
