# Generated by Django 2.1.7 on 2019-03-27 05:58

import django.db.models.deletion
from django.db import migrations, models

import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("wagtailimages", "__latest__"), ("wagtailcore", "__latest__")]

    operations = [
        migrations.CreateModel(
            name="SimplePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(wagtailmetadata.models.MetadataMixin, "wagtailcore.page", models.Model),
        )
    ]
